# Generated by Django 4.1.1 on 2022-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
    ]
