# Generated by Django 4.1.1 on 2022-09-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_posted', models.DateField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
