# Generated by Django 4.1.1 on 2022-09-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog_header_image_blog_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=400)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=600, unique=True)),
                ('profile_pic', models.TextField(default='img/default.png')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40)),
                ('comment_text', models.TextField()),
                ('date_posted', models.DateField()),
                ('likes', models.IntegerField()),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comment'),
        ),
    ]
