# Generated by Django 4.1.1 on 2022-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_remove_blog_name_remove_blog_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
