# Generated by Django 4.1.1 on 2022-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_slug_alter_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
