# Generated by Django 4.1.1 on 2022-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_uname_user_fname_user_lname_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
