# Generated by Django 4.1.1 on 2022-09-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_blog_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.post_categories'),
        ),
    ]
