# Generated by Django 4.1.1 on 2022-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_blog_category_post_categories_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_categories',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='home.post_categories'),
        ),
    ]
