# Generated by Django 4.1.1 on 2022-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_post_categories_blogs_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_categories',
            name='blogs',
            field=models.ManyToManyField(to='home.blog'),
        ),
    ]
