# Generated by Django 4.1.1 on 2022-09-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
    ]
